### PR TITLE
fix outdated headers, extra whitespace, and autogen problem

### PR DESCRIPTION
**Pull request by garlick**
Fix a few minor problems that should have been addressed a long time ago.

All the changes here are cosmetic, except 
* Pulling in libgcrypt.m4 affects `autogen.sh` (not builds from dist tarballs)
* Substituting version from `git describe` instead of META into man page and spec file at configure time.

### CODE REVIEW

**Review by chu11 — APPROVED** [review]
LGTM.  Just one comment on the AUTHORS removal.  The AUTHORS list might be useful to keep for AUTHORS pre-git.  Some of that pre-git history may have been lost during conversion.  As an example, I tried to see if the "John Allen" was anywhere in the git log, and its not.

It's ultimately your call.  LMK decision and then I can hit merge button.

**Comment by garlick** [comment]
I had added some people who reviewed a major revision, but I'm thinking they probably don't consider themselves "authors" anyway.   I don't think there are any other actual contributors who are listed in AUTHORS and not in the git history.  I say nix it.

**Comment by chu11** [comment]
@garlick sounds good hitting the button

**Comment by garlick** [comment]
Thanks!

**Comment by pete4abw** [comment]
Getting rid of META and using only git describe in configure.ac will cause any user who downloads a tarball to be unable to compile. The purpose of META. I've seen this in other implementations I work on. Was this carefully reviewed?

**Comment by garlick** [comment]
There should be no problem getting rid of META as the substituion happens during autogen not configure (hence not applicable to a dist tarball), but I should have run a `make distcheck` as part of submitting this, and in fact now that I run it, I see I forgot a couple of minor things.  New PR coming.  Thanks @pete4abw.

**Comment by garlick** [comment]
Oh yeah, `make distcheck` doesn't work because VPATH builds don't work yet here.  Sigh.  I'll open a bug.

**Pull request merged**
